### ISSUE TITLE
[Bug] Cannot use copy/paste with mouse into Wallet Connect dialog box

### ISSUE THREAD

**Issue by JE2530** [Chia-Network/chia-blockchain-gui#2267]
### What happened?

Wallet Connect Integration: Add connection feature is not allowing me to paste link * I have to use keyboard short cut and the drop down for Select Keys isn't functioning either. 

### Version

2.1.4

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by ChiaMineJP** [comment]
I'd like to confirm one thing. What do you mean copy/paste by mouse?
Did you expect that right clicking on text inputs shows context menu with copy/paste menu item?

**Comment by markelrod** [comment]
@JE2530 - Did you see the question above? Please provide more detail. Are you trying to use the context menu or are you trying to paste with the middle button under linux?

**Comment by markelrod** [comment]
@ChiaMineJP - There are two separate things reported:

1) Context menu for paste in text input - Currently we do not  support context menu for paste in any text input so let's hold off on this for now.

2) Drop down for Select Keys isn't functioning - Can we confirm this? If that is the case we should fix it.

**Comment by ChiaMineJP** [comment]
Ok, I'll check `2.`

**Comment by ChiaMineJP** [comment]
https://github.com/Chia-Network/chia-blockchain-gui/assets/84098616/78f98aa5-ad2f-496d-92c7-236b23e40a63

`Select keys` seems working fine.
Did you try the latest version(`2.4.1`)?

**Comment by wjblanke** [comment]
JE2530: Can u try with 2.4.2 and leave a video showing the issue if u still have problems?

**Comment by markelrod** [comment]
@JE2530 - We are closing this issue since we have not received more info from you. Based on our investigation:

1. Select Keys appears to work fine on latest version
2. Context menu for paste in text input is not going to be added at this point

**Comment by JE2530** [comment]
Thank you
